#:schema node_modules/wrangler/config-schema.json
name = "catts-query-proxy"
main = "src/index.ts"
compatibility_date = "2024-05-12"

[[durable_objects.bindings]]
name = "CATTS_QUERY_PROXY"
class_name = "ProxyRequestDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["ProxyRequestDurableObject"]
